### ISSUE TITLE
Command failed: remix routes --json | tee in Windows Powershell

### ISSUE THREAD

**Issue by homumado** [sandulat/routes-gen#24]
### Describe the bug

Followed the instructions up to this line `yarn routes-gen -d @routes-gen/remix` and received the following error:

![image](https://user-images.githubusercontent.com/84349818/193714543-165dfd00-df41-4c42-aa6a-a6be3cc4ef3f.png)

I believe this occurs because on Windows it defaults to use command prompt instead of Powershell, where the command would have worked.

### Your Example Website or App

n/a

### Steps to Reproduce the Bug or Issue

1. Open existing remix repo on VSCode Windows
2. `yarn add routes-gen @routes-gen/remix`
3. `yarn routes-gen -d @routes-gen/remix`

### Expected behavior

It will parse and export the routes, based on the driver that you've provided.

### Platform

- OS: Windows 10 Powershell
- IDE: VSCode

**Comment by sandulat** [comment]
@homumado I do not have a Windows myself. Do you have any ideas on how we could approach this?

**Comment by sandulat** [comment]
I've added `tee` to get the full output of `remix routes --json`. The output can be very long when you have many routes, and without `tee`, it gets truncated. Not sure if there's a cross-platform alternative to `tee`.

**Comment by sandulat** [comment]
@homumado I think a solution might be ditching `exec` in favour of using Remix internal utils for reading the routes. 

Pros:
- Cross-platform.
- Insane speed bump. Locally, it went down from `5.03s` to `0.30s` for me.

Cons:
- We're using internals, which may break on any Remix release.

I'm still researching for the best approach.

**Comment by sandulat** [comment]
@homumado This was fixed in `@routes-gen/remix` `0.3.4`. You can upgrade with `yarn add @routes-gen/remix@latest`. Feel free to re-open this issue or another one, if you still encounter any issues after upgrading.

**Comment by homumado** [comment]
Yey it works! Thanks for kicking ass, @sandulat !

![image](https://user-images.githubusercontent.com/84349818/193929027-1a411e91-9035-489f-a4be-351f7389b26c.png)

**Comment by sandulat** [comment]
Awesome! Glad it works!
