### ISSUE TITLE
Routes gen remix requires use of --legacy-peer-deps when used with Remix 2.x

### ISSUE THREAD

**Issue by andersr** [sandulat/routes-gen#40]
### Describe the bug

After updating remix to v2.x, and installing packages, I get the following error:

```sh
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @routes-gen/remix@0.3.6
npm ERR! Found: @remix-run/dev@2.1.0
npm ERR! node_modules/@remix-run/dev
npm ERR!   dev @remix-run/dev@"2.1.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @remix-run/dev@"^1.0.3" from @routes-gen/remix@0.3.6
npm ERR! node_modules/@routes-gen/remix
npm ERR!   dev @routes-gen/remix@"^0.3.6" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @remix-run/dev@1.19.3
npm ERR! node_modules/@remix-run/dev
npm ERR!   peer @remix-run/dev@"^1.0.3" from @routes-gen/remix@0.3.6
npm ERR!   node_modules/@routes-gen/remix
npm ERR!     dev @routes-gen/remix@"^0.3.6" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resol
```

Due to the above outdated peer dependencies for `@routes-gen/remix` it is now required to use `--legacy-peer-deps` with every npm install or uninstall command.

Would it be possible to update the peer dependencies?

### Your Example Website or App

https://stackblitz.com/edit/remix-run-remix-yqj3cg?file=package.json

### Steps to Reproduce the Bug or Issue

1. Run ` npm i -D routes-gen @routes-gen/remix `
2. Error shown above displays

### Expected behavior

Run npm install or uninstall without errors.

### Platform

- OS:  macOS

**Comment by sandulat** [comment]
Thank you, @andersr! This issue has been resolved in `@routes-gen/remix` version `0.3.7`.

Please feel free to reopen it if you encounter the issue again.
